openapi: 3.0.1
info:
  title: 微信公众号素材相关接口
  version: 1.0.0
servers:
- url: https://api.weixin.qq.com/cgi-bin
paths:
  /material/batchget_material:
    post:
      parameters:
      - description: access_token
        explode: true
        in: query
        name: access_token
        required: true
        schema:
          type: string
        style: form
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BatchgetMaterialRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchgetMaterialResponse'
          description: ""
      summary: 素材管理 /获取素材列表
      tags:
      - material
  /material/get_material:
    post:
      parameters:
      - description: access_token
        explode: true
        in: query
        name: access_token
        required: true
        schema:
          type: string
        style: form
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetMaterialRequest'
        required: true
      responses:
        "200":
          content:
            multipart/form-data:
              schema:
                format: binary
                type: string
          description: 根据获取的素材类型有不同的值
      summary: 素材管理 /获取永久素材
      tags:
      - material
components:
  schemas:
    GetMaterialRequest:
      example:
        media_id: media_id
      properties:
        media_id:
          description: 要获取的素材的media_id
          type: string
    BatchgetMaterialRequest:
      example:
        offset: 0
        count: 6
        type: type
      properties:
        type:
          description: 素材的类型，图片（image）、视频（video）、语音 （voice）、图文（news）
          type: string
        offset:
          description: 从全部素材的该偏移位置开始返回，0表示从第一个素材 返回
          type: integer
        count:
          description: 返回素材的数量，取值在1到20之间
          type: integer
    BatchgetMaterialResponse:
      example:
        errcode: 0
        item_count: 1
        item:
        - update_time: 5
          name: name
          media_id: media_id
          content:
            news_item:
            - thumb_url: thumb_url
              thumb_media_id: thumb_media_id
              author: author
              show_cover_pic: 5
              digest: digest
              content_source_url: content_source_url
              title: title
              content: content
              url: url
            - thumb_url: thumb_url
              thumb_media_id: thumb_media_id
              author: author
              show_cover_pic: 5
              digest: digest
              content_source_url: content_source_url
              title: title
              content: content
              url: url
          url: url
        - update_time: 5
          name: name
          media_id: media_id
          content:
            news_item:
            - thumb_url: thumb_url
              thumb_media_id: thumb_media_id
              author: author
              show_cover_pic: 5
              digest: digest
              content_source_url: content_source_url
              title: title
              content: content
              url: url
            - thumb_url: thumb_url
              thumb_media_id: thumb_media_id
              author: author
              show_cover_pic: 5
              digest: digest
              content_source_url: content_source_url
              title: title
              content: content
              url: url
          url: url
        total_count: 6
        errmsg: errmsg
      properties:
        errcode:
          description: 返回码
          type: integer
        errmsg:
          description: 对返回码的文本描述内容
          type: string
        total_count:
          description: 该类型的素材的总数
          type: integer
        item_count:
          description: 本次调用获取的素材的数量
          type: integer
        item:
          items:
            $ref: '#/components/schemas/BatchgetMaterialResponse_item_inner'
          type: array
    BatchgetMaterialResponse_item_inner_content_news_item_inner:
      example:
        thumb_url: thumb_url
        thumb_media_id: thumb_media_id
        author: author
        show_cover_pic: 5
        digest: digest
        content_source_url: content_source_url
        title: title
        content: content
        url: url
      properties:
        title:
          description: 图文消息的标题
          type: string
        thumb_media_id:
          description: 图文消息的封面图片素材id（必须是永久mediaID）
          type: string
        show_cover_pic:
          description: 是否显示封面，0为false，即不显示，1为true，即显示
          type: integer
        author:
          description: 作者
          type: string
        digest:
          description: 图文消息的摘要，仅有单图文消息才有摘要，多图文此处为空
          type: string
        content:
          description: 图文消息的具体内容，支持HTML标签，必须少于2万字符，小于1M，且此处会去除JS
          type: string
        content_source_url:
          description: 图文消息的原文地址，即点击“阅读原文”后的URL
          type: string
        url:
          description: 图文页的URL，或者，当获取的列表是图片素材列表时，该字段是图片的URL
          type: string
        thumb_url:
          description: 封面URL
          type: string
      type: object
    BatchgetMaterialResponse_item_inner_content:
      example:
        news_item:
        - thumb_url: thumb_url
          thumb_media_id: thumb_media_id
          author: author
          show_cover_pic: 5
          digest: digest
          content_source_url: content_source_url
          title: title
          content: content
          url: url
        - thumb_url: thumb_url
          thumb_media_id: thumb_media_id
          author: author
          show_cover_pic: 5
          digest: digest
          content_source_url: content_source_url
          title: title
          content: content
          url: url
      properties:
        news_item:
          items:
            $ref: '#/components/schemas/BatchgetMaterialResponse_item_inner_content_news_item_inner'
          type: array
      type: object
    BatchgetMaterialResponse_item_inner:
      example:
        update_time: 5
        name: name
        media_id: media_id
        content:
          news_item:
          - thumb_url: thumb_url
            thumb_media_id: thumb_media_id
            author: author
            show_cover_pic: 5
            digest: digest
            content_source_url: content_source_url
            title: title
            content: content
            url: url
          - thumb_url: thumb_url
            thumb_media_id: thumb_media_id
            author: author
            show_cover_pic: 5
            digest: digest
            content_source_url: content_source_url
            title: title
            content: content
            url: url
        url: url
      properties:
        media_id:
          type: string
        content:
          $ref: '#/components/schemas/BatchgetMaterialResponse_item_inner_content'
        url:
          description: 图文页的URL，或者，当获取的列表是图片素材列表时，该字段是图片的URL
          type: string
        update_time:
          description: 这篇图文消息素材的最后更新时间
          format: int64
          type: integer
        name:
          description: 文件名称
          type: string
      type: object
