openapi: 3.0.1
info:
  title: 微信第三方平台授权相关接口
  version: 1.0.0
servers:
- url: https://api.weixin.qq.com/cgi-bin
paths:
  /component/api_get_authorizer_info:
    post:
      parameters:
      - description: 第三方平台component_access_token，不是authorizer_access_token
        explode: true
        in: query
        name: component_access_token
        required: true
        schema:
          type: string
        style: form
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetAuthorizerInfoRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAuthorizerInfoResponse'
          description: ""
      summary: 获取授权方的帐号基本信息
      tags:
      - auth
  /component/api_authorizer_token:
    post:
      parameters:
      - description: 第三方平台component_access_token，不是authorizer_access_token
        explode: true
        in: query
        name: component_access_token
        required: true
        schema:
          type: string
        style: form
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthorizerTokenRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthorizerTokenResponse'
          description: ""
      summary: 获取/刷新接口调用令牌
      tags:
      - auth
  /component/api_query_auth:
    post:
      parameters:
      - description: 第三方平台component_access_token，不是authorizer_access_token
        explode: true
        in: query
        name: component_access_token
        required: true
        schema:
          type: string
        style: form
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryAuthRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryAuthResponse'
          description: ""
      summary: 使用授权码获取授权信息
      tags:
      - auth
  /component/api_create_preauthcode:
    post:
      parameters:
      - description: 第三方平台component_access_token，不是authorizer_access_token
        explode: true
        in: query
        name: component_access_token
        required: true
        schema:
          type: string
        style: form
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePreauthcodeRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreatePreauthcodeResponse'
          description: 预授权码（pre_auth_code）是第三方平台方实现授权托管的必备信息，每个预授权码有效期为 1800秒。需要先获取令牌才能调用。使用过程中如遇到问题，可在开放平台服务商专区发帖交流。
      summary: 预授权码
      tags:
      - auth
  /component/api_component_token:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ComponentTokenRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ComponentTokenResponse'
          description: 令牌（component_access_token）是第三方平台接口的调用凭据。令牌的获取是有限制的，每个令牌的有效期为
            2 小时，请自行做好令牌的管理，在令牌快过期时（比如1小时50分），重新调用接口获取。
      summary: 令牌
      tags:
      - auth
  /component/api_start_push_ticket:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StartPushTicketRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StartPushTicketResponse'
          description: 该 API 用于启动ticket推送服务。使用过程中如遇到问题，可在开放平台服务商专区发帖交流。
      summary: 启动ticket推送服务
      tags:
      - auth
components:
  schemas:
    GetAuthorizerInfoRequest:
      example:
        component_appid: component_appid
        authorizer_appid: authorizer_appid
      properties:
        component_appid:
          description: 平台型第三方平台的appid
          type: string
        authorizer_appid:
          description: 授权方 appid
          type: string
      required:
      - authorizer_appid
      - component_appid
    GetAuthorizerInfoResponse:
      example:
        errcode: 0
        authorizer_info:
          qrcode_url: qrcode_url
          business_info:
            open_pay: 2
            open_card: 7
            open_store: 5
            open_scan: 5
            open_shake: 9
          signature: signature
          user_name: user_name
          nick_name: nick_name
          head_img: head_img
          principal_name: principal_name
          alias: alias
          MiniProgramInfo:
            visit_status: 3
            categories:
            - first: first
              second: second
            - first: first
              second: second
            network:
              WsRequestDomain:
              - WsRequestDomain
              - WsRequestDomain
              UDPDomain:
              - UDPDomain
              - UDPDomain
              BizDomain:
              - BizDomain
              - BizDomain
              RequestDomain:
              - RequestDomain
              - RequestDomain
              UploadDomain:
              - UploadDomain
              - UploadDomain
              DownloadDomain:
              - DownloadDomain
              - DownloadDomain
          verify_type_info:
            id: 1
          service_type_info:
            id: 6
        errmsg: errmsg
        authorization_info:
          authorization_appid: authorization_appid
          func_info:
          - funcscope_category:
              id: 2
          - funcscope_category:
              id: 2
      properties:
        errcode:
          description: 返回码
          type: integer
        errmsg:
          description: 对返回码的文本描述内容
          type: string
        authorizer_info:
          $ref: '#/components/schemas/GetAuthorizerInfoResponse_authorizer_info'
        authorization_info:
          $ref: '#/components/schemas/GetAuthorizerInfoResponse_authorization_info'
    AuthorizerTokenRequest:
      example:
        component_appid: component_appid
        authorizer_appid: authorizer_appid
        authorizer_refresh_token: authorizer_refresh_token
      properties:
        component_appid:
          description: 平台型第三方平台的appid
          type: string
        authorizer_appid:
          description: 授权方 appid
          type: string
        authorizer_refresh_token:
          description: 刷新令牌，获取授权信息时得到
          type: string
      required:
      - authorizer_appid
      - authorizer_refresh_token
      - component_appid
    AuthorizerTokenResponse:
      example:
        errcode: 0
        authorizer_access_token: authorizer_access_token
        authorizer_refresh_token: authorizer_refresh_token
        errmsg: errmsg
        expires_in: 6
      properties:
        errcode:
          description: 返回码
          type: integer
        errmsg:
          description: 对返回码的文本描述内容
          type: string
        expires_in:
          description: 有效期，单位：秒
          type: integer
        authorizer_access_token:
          description: 授权方令牌
          type: string
        authorizer_refresh_token:
          description: 刷新令牌
          type: string
    QueryAuthRequest:
      example:
        component_appid: component_appid
        authorization_code: authorization_code
      properties:
        component_appid:
          description: 平台型第三方平台的appid
          type: string
        authorization_code:
          description: "授权码, 会在授权成功时返回给第三方平台，详见第三方平台授权流程说明"
          type: string
      required:
      - authorization_code
      - component_appid
    QueryAuthResponse:
      example:
        errcode: 0
        errmsg: errmsg
        authorization_info:
          authorizer_appid: authorizer_appid
          authorizer_access_token: authorizer_access_token
          authorizer_refresh_token: authorizer_refresh_token
          expires_in: 6
          func_info:
          - funcscope_category:
              id: 2
          - funcscope_category:
              id: 2
      properties:
        errcode:
          description: 返回码
          type: integer
        errmsg:
          description: 对返回码的文本描述内容
          type: string
        authorization_info:
          $ref: '#/components/schemas/QueryAuthResponse_authorization_info'
    CreatePreauthcodeRequest:
      example:
        component_appid: component_appid
      properties:
        component_appid:
          description: 平台型第三方平台的appid
          type: string
      required:
      - component_appid
    CreatePreauthcodeResponse:
      example:
        errcode: 0
        errmsg: errmsg
        expires_in: 6
        pre_auth_code: pre_auth_code
      properties:
        errcode:
          description: 返回码
          type: integer
        errmsg:
          description: 对返回码的文本描述内容
          type: string
        expires_in:
          description: 有效期，单位：秒
          type: integer
        pre_auth_code:
          description: 预授权码
          type: string
    ComponentTokenRequest:
      example:
        component_appid: component_appid
        component_verify_ticket: component_verify_ticket
        component_appsecret: component_appsecret
      properties:
        component_appid:
          description: 平台型第三方平台的appid
          type: string
        component_appsecret:
          description: 第三方平台 appsecret
          type: string
        component_verify_ticket:
          description: 微信后台推送的 ticket
          type: string
      required:
      - component_appid
      - component_appsecret
      - component_verify_ticket
    ComponentTokenResponse:
      example:
        errcode: 0
        errmsg: errmsg
        component_access_token: component_access_token
        expires_in: 6
      properties:
        errcode:
          description: 返回码
          type: integer
        errmsg:
          description: 对返回码的文本描述内容
          type: string
        expires_in:
          description: 有效期，单位：秒
          type: integer
        component_access_token:
          description: 第三方平台 access_token
          type: string
    StartPushTicketRequest:
      example:
        component_appid: component_appid
        component_secret: component_secret
      properties:
        component_appid:
          description: 平台型第三方平台的appid
          type: string
        component_secret:
          description: 平台型第三方平台的APPSECRET
          type: string
      required:
      - component_appid
      - component_secret
    StartPushTicketResponse:
      example:
        errcode: 0
        errmsg: errmsg
      properties:
        errcode:
          description: 返回码
          type: integer
        errmsg:
          description: 对返回码的文本描述内容
          type: string
    GetAuthorizerInfoResponse_authorizer_info_service_type_info:
      description: 公众号类型
      example:
        id: 6
      properties:
        id:
          type: integer
      type: object
    GetAuthorizerInfoResponse_authorizer_info_verify_type_info:
      description: 公众号认证类型
      example:
        id: 1
      properties:
        id:
          type: integer
      type: object
    GetAuthorizerInfoResponse_authorizer_info_business_info:
      description: 用以了解功能的开通状况（0代表未开通，1代表已开通），详见business_info 说明
      example:
        open_pay: 2
        open_card: 7
        open_store: 5
        open_scan: 5
        open_shake: 9
      properties:
        open_store:
          description: 是否开通微信门店功能
          type: integer
        open_scan:
          description: 是否开通微信扫商品功能
          type: integer
        open_pay:
          description: 是否开通微信支付功能
          type: integer
        open_card:
          description: 是否开通微信卡券功能
          type: integer
        open_shake:
          description: 是否开通微信摇一摇功能
          type: integer
      type: object
    GetAuthorizerInfoResponse_authorizer_info_MiniProgramInfo_network:
      example:
        WsRequestDomain:
        - WsRequestDomain
        - WsRequestDomain
        UDPDomain:
        - UDPDomain
        - UDPDomain
        BizDomain:
        - BizDomain
        - BizDomain
        RequestDomain:
        - RequestDomain
        - RequestDomain
        UploadDomain:
        - UploadDomain
        - UploadDomain
        DownloadDomain:
        - DownloadDomain
        - DownloadDomain
      properties:
        RequestDomain:
          items:
            type: string
          type: array
        WsRequestDomain:
          items:
            type: string
          type: array
        UploadDomain:
          items:
            type: string
          type: array
        DownloadDomain:
          items:
            type: string
          type: array
        BizDomain:
          items:
            type: string
          type: array
        UDPDomain:
          items:
            type: string
          type: array
      type: object
    GetAuthorizerInfoResponse_authorizer_info_MiniProgramInfo_categories_inner:
      example:
        first: first
        second: second
      properties:
        first:
          description: 帐号介绍
          type: string
        second:
          description: 帐号介绍
          type: string
      type: object
    GetAuthorizerInfoResponse_authorizer_info_MiniProgramInfo:
      description: 小程序配置，根据这个字段判断是否为小程序类型授权
      example:
        visit_status: 3
        categories:
        - first: first
          second: second
        - first: first
          second: second
        network:
          WsRequestDomain:
          - WsRequestDomain
          - WsRequestDomain
          UDPDomain:
          - UDPDomain
          - UDPDomain
          BizDomain:
          - BizDomain
          - BizDomain
          RequestDomain:
          - RequestDomain
          - RequestDomain
          UploadDomain:
          - UploadDomain
          - UploadDomain
          DownloadDomain:
          - DownloadDomain
          - DownloadDomain
      properties:
        visit_status:
          type: integer
        network:
          $ref: '#/components/schemas/GetAuthorizerInfoResponse_authorizer_info_MiniProgramInfo_network'
        categories:
          items:
            $ref: '#/components/schemas/GetAuthorizerInfoResponse_authorizer_info_MiniProgramInfo_categories_inner'
          type: array
      type: object
    GetAuthorizerInfoResponse_authorizer_info:
      example:
        qrcode_url: qrcode_url
        business_info:
          open_pay: 2
          open_card: 7
          open_store: 5
          open_scan: 5
          open_shake: 9
        signature: signature
        user_name: user_name
        nick_name: nick_name
        head_img: head_img
        principal_name: principal_name
        alias: alias
        MiniProgramInfo:
          visit_status: 3
          categories:
          - first: first
            second: second
          - first: first
            second: second
          network:
            WsRequestDomain:
            - WsRequestDomain
            - WsRequestDomain
            UDPDomain:
            - UDPDomain
            - UDPDomain
            BizDomain:
            - BizDomain
            - BizDomain
            RequestDomain:
            - RequestDomain
            - RequestDomain
            UploadDomain:
            - UploadDomain
            - UploadDomain
            DownloadDomain:
            - DownloadDomain
            - DownloadDomain
        verify_type_info:
          id: 1
        service_type_info:
          id: 6
      properties:
        nick_name:
          description: 昵称
          type: string
        head_img:
          description: 头像
          type: string
        service_type_info:
          $ref: '#/components/schemas/GetAuthorizerInfoResponse_authorizer_info_service_type_info'
        verify_type_info:
          $ref: '#/components/schemas/GetAuthorizerInfoResponse_authorizer_info_verify_type_info'
        user_name:
          description: 原始 ID
          type: string
        principal_name:
          description: 主体名称
          type: string
        alias:
          description: 公众号所设置的微信号，可能为空
          type: string
        business_info:
          $ref: '#/components/schemas/GetAuthorizerInfoResponse_authorizer_info_business_info'
        qrcode_url:
          description: 二维码图片的 URL，开发者最好自行也进行保存
          type: string
        signature:
          description: 帐号介绍
          type: string
        MiniProgramInfo:
          $ref: '#/components/schemas/GetAuthorizerInfoResponse_authorizer_info_MiniProgramInfo'
      type: object
    GetAuthorizerInfoResponse_authorization_info_func_info_inner_funcscope_category:
      example:
        id: 2
      properties:
        id:
          type: integer
      type: object
    GetAuthorizerInfoResponse_authorization_info_func_info_inner:
      example:
        funcscope_category:
          id: 2
      properties:
        funcscope_category:
          $ref: '#/components/schemas/GetAuthorizerInfoResponse_authorization_info_func_info_inner_funcscope_category'
      type: object
    GetAuthorizerInfoResponse_authorization_info:
      example:
        authorization_appid: authorization_appid
        func_info:
        - funcscope_category:
            id: 2
        - funcscope_category:
            id: 2
      properties:
        authorization_appid:
          description: 授权方 appid
          type: string
        func_info:
          description: 授权给开发者的权限集列表
          items:
            $ref: '#/components/schemas/GetAuthorizerInfoResponse_authorization_info_func_info_inner'
          type: array
      type: object
    QueryAuthResponse_authorization_info:
      example:
        authorizer_appid: authorizer_appid
        authorizer_access_token: authorizer_access_token
        authorizer_refresh_token: authorizer_refresh_token
        expires_in: 6
        func_info:
        - funcscope_category:
            id: 2
        - funcscope_category:
            id: 2
      properties:
        authorizer_appid:
          description: 授权方 appid
          type: string
        authorizer_access_token:
          description: 接口调用令牌（在授权的公众号/小程序具备 API 权限时，才有此返回值）
          type: string
        expires_in:
          description: authorizer_access_token 的有效期（在授权的公众号/小程序具备API权限时，才有此返回值），单位：秒
          type: integer
        authorizer_refresh_token:
          description: 刷新令牌（在授权的公众号具备API权限时，才有此返回值），刷新令牌主要用于第三方平台获取和刷新已授权用户的 authorizer_access_token。一旦丢失，只能让用户重新授权，才能再次拿到新的刷新令牌。用户重新授权后，之前的刷新令牌会失效
          type: string
        func_info:
          description: 授权给开发者的权限集列表
          items:
            $ref: '#/components/schemas/GetAuthorizerInfoResponse_authorization_info_func_info_inner'
          type: array
      type: object
